const $=id=>document.getElementById(id);
const DB_NAME='vinskap-db',DB_VERSION=1;
let db,activeFilter='all',activeWineId='',activeExperienceId='';

function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
function safe(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function formatDate(v){if(!v)return '';const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('nb-NO',{day:'numeric',month:'long',year:'numeric'}).format(d)}
function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false')}
function closeModal(id){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true')}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function getAll(name){return new Promise((r,j)=>{const q=store(name).getAll();q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
function put(name,value){return new Promise((r,j)=>{const q=store(name,'readwrite').put(value);q.onsuccess=()=>r(value);q.onerror=()=>j(q.error)})}
function remove(name,id){return new Promise((r,j)=>{const q=store(name,'readwrite').delete(id);q.onsuccess=()=>r();q.onerror=()=>j(q.error)})}
function clearStore(name){return new Promise((r,j)=>{const q=store(name,'readwrite').clear();q.onsuccess=()=>r();q.onerror=()=>j(q.error)})}

function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('wines'))d.createObjectStore('wines',{keyPath:'id'});if(!d.objectStoreNames.contains('trips'))d.createObjectStore('trips',{keyPath:'id'})};req.onsuccess=()=>{db=req.result;resolve()};req.onerror=()=>reject(req.error)})}

async function migrateOldTripWines(){
  if(localStorage.getItem('vinbok-trip-migration-v1'))return;
  const [wines,trips]=await Promise.all([getAll('wines'),getAll('trips')]);
  const keys=new Set(wines.map(w=>w.migratedFromTripWine).filter(Boolean));
  for(const trip of trips){for(const w of trip.wines||[]){const key=`${trip.id}:${w.id}`;if(keys.has(key))continue;await put('wines',{id:uid(),name:w.name||'Vin',vintage:w.vintage||'',type:w.type||'Rødvin',producer:w.producer||'',country:w.country||'',region:w.region||'',grapes:w.grapes||'',notes:w.text||w.notes||'',image:w.image||'',experienceId:trip.id,rating:w.rating||'',favorite:Boolean(w.favorite),buyAgain:Boolean(w.buyAgain),tastedAt:w.tastedAt||trip.date||'',place:w.place||'',people:w.people||'',createdAt:w.createdAt||trip.createdAt||Date.now(),migratedFromTripWine:key})}}
  localStorage.setItem('vinbok-trip-migration-v1','done');
}

function wineImage(w){return w.image||w.labelImage||''}
function stars(n){return n?`${'★'.repeat(Number(n))}${'☆'.repeat(5-Number(n))}`:''}
function wineCard(w){const image=wineImage(w),flags=`${w.favorite?'♥':''}${w.buyAgain?' ↻':''}`;return `<article class="wine-card"><button class="wine-open" data-wine="${safe(w.id)}" aria-label="Åpne ${safe(w.name||'vin')} og se informasjon og notater">${image?`<img class="wine-image" src="${image}" alt="${safe(w.name)}">`:'<div class="wine-placeholder">VIN</div>'}<div class="wine-body"><span class="badge">${safe(w.type||'Vin')}</span><span class="card-flags">${flags}</span><h3>${safe(w.name||'Uten navn')}</h3><p>${safe([w.producer,w.vintage].filter(Boolean).join(' · '))}</p>${w.rating?`<div class="stars">${stars(w.rating)}</div>`:''}</div><span class="wine-cta">Se info og notater ›</span></button></article>`}
function experienceCard(e,wines){const count=wines.filter(w=>w.experienceId===e.id).length;return `<article class="experience-card"><button class="experience-open" data-experience="${safe(e.id)}">${e.image?`<img class="experience-cover" src="${e.image}" alt="${safe(e.name)}">`:'<div class="experience-placeholder">VINREISE</div>'}<div class="experience-body"><span class="travel-badge">REISE</span><h3>${safe(e.name||'Reise')}</h3>${e.text?`<p>${safe(e.text)}</p>`:''}<div class="experience-meta"><span>${formatDate(e.date||'')}</span><span>${count} ${count===1?'vin':'viner'}</span></div></div></button></article>`}

async function render(){
  const [wines,experiences]=await Promise.all([getAll('wines'),getAll('trips')]);
  const personalWines=wines.filter(w=>!w.experienceId);
  $('wineCount').textContent=personalWines.length;$('favoriteCount').textContent=personalWines.filter(w=>w.favorite).length;$('experienceCount').textContent=experiences.length;
  const query=($('wineSearch').value||'').trim().toLowerCase(),type=$('wineTypeFilter').value;
  const filtered=personalWines.filter(w=>(!type||w.type===type)&&(!query||JSON.stringify(w).toLowerCase().includes(query))&&(activeFilter==='all'||(activeFilter==='favorite'&&w.favorite)||(activeFilter==='again'&&w.buyAgain))).sort((a,b)=>(b.tastedAt||'').localeCompare(a.tastedAt||'')||(b.createdAt||0)-(a.createdAt||0));
  $('wineList').innerHTML=filtered.length?filtered.map(wineCard).join(''):'<div class="empty">Ingen viner her ennå. Trykk «Ny vin» for å legge til den første.</div>';
  $('experienceList').innerHTML=experiences.length?[...experiences].sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.createdAt||0)-(a.createdAt||0)).map(e=>experienceCard(e,wines)).join(''):'<div class="empty">Ingen reiser lagret ennå.</div>';
  if(activeExperienceId&&$('experienceDetailModal').classList.contains('open'))await fillExperienceDetail();
}

function resetWineForm(experienceId='',travelName=''){$('wineForm').reset();$('wineId').value='';$('wineImage').value='';$('wineImagePreview').src='';$('wineImagePreview').hidden=true;$('wineFormTitle').textContent=experienceId?'Legg til vin på reisen':'Legg til vin';$('tastedAt').value=today();$('experienceId').value=experienceId;$('travelContext').hidden=!experienceId;$('travelContext').textContent=experienceId?`Denne vinen lagres bare på reisen «${travelName}».`:''}
async function editWine(id){const [wines,travels]=await Promise.all([getAll('wines'),getAll('trips')]);const w=wines.find(x=>x.id===id);if(!w)return;const travel=travels.find(x=>x.id===w.experienceId);resetWineForm(w.experienceId||'',travel?.name||'');$('wineId').value=w.id;$('wineFormTitle').textContent='Rediger vin';['name','vintage','type','producer','country','region','grapes','tastedAt','place','people','rating','notes'].forEach(k=>{if($(k))$(k).value=w[k]??''});$('favorite').checked=Boolean(w.favorite);$('buyAgain').checked=Boolean(w.buyAgain);$('wineImage').value=wineImage(w);$('wineImagePreview').src=wineImage(w);$('wineImagePreview').hidden=!wineImage(w);closeModal('wineDetailModal');openModal('wineModal')}
async function openWineDetail(id){const [wines,experiences]=await Promise.all([getAll('wines'),getAll('trips')]);const w=wines.find(x=>x.id===id);if(!w)return;activeWineId=id;const e=experiences.find(x=>x.id===w.experienceId),image=wineImage(w);$('detailImage').src=image;$('detailImage').hidden=!image;$('detailType').textContent=w.type||'Vin';$('detailName').textContent=w.name||'Vin';const meta=[[w.producer,w.vintage].filter(Boolean).join(' · '),[w.country,w.region].filter(Boolean).join(' · '),w.grapes?`Druer: ${w.grapes}`:'',w.tastedAt?formatDate(w.tastedAt):'',w.place?`Sted: ${w.place}`:'',w.people?`Sammen med: ${w.people}`:'',e?`Reise: ${e.name}`:''].filter(Boolean);$('detailMeta').innerHTML=meta.map(x=>`<div>${safe(x)}</div>`).join('');$('detailRating').textContent=stars(w.rating);$('detailNotes').textContent=w.notes||'';$('detailNotes').hidden=!w.notes;$('detailFlags').innerHTML=`${w.favorite?'<span class="flag">♥ Favoritt</span>':''}${w.buyAgain?'<span class="flag">↻ Vil kjøpe igjen</span>':''}`;openModal('wineDetailModal')}

function resetExperienceForm(){$('experienceForm').reset();$('experienceEditId').value='';$('experienceImage').value='';$('experienceImagePreview').src='';$('experienceImagePreview').hidden=true;$('experienceDate').value=today();$('experienceFormTitle').textContent='Ny reise'}
async function editExperience(id){const e=(await getAll('trips')).find(x=>x.id===id);if(!e)return;resetExperienceForm();$('experienceEditId').value=e.id;$('experienceFormTitle').textContent='Rediger reise';$('experienceName').value=e.name||'';$('experienceDate').value=e.date||'';$('experienceText').value=e.text||'';$('experienceImage').value=e.image||'';$('experienceImagePreview').src=e.image||'';$('experienceImagePreview').hidden=!e.image;closeModal('experienceDetailModal');openModal('experienceModal')}
async function openExperienceDetail(id){activeExperienceId=id;await fillExperienceDetail();openModal('experienceDetailModal')}
async function fillExperienceDetail(){const [experiences,wines]=await Promise.all([getAll('trips'),getAll('wines')]);const e=experiences.find(x=>x.id===activeExperienceId);if(!e)return;$('experienceDetailImage').src=e.image||'';$('experienceDetailImage').hidden=!e.image;$('experienceDetailTitle').textContent=e.name||'Reise';$('experienceDetailDate').textContent=formatDate(e.date||'');$('experienceDetailText').textContent=e.text||'';$('experienceDetailText').hidden=!e.text;const list=wines.filter(w=>w.experienceId===e.id).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('experienceWineList').innerHTML=list.length?list.map(wineCard).join(''):'<div class="empty">Ingen viner på denne reisen ennå.</div>'}

function fileToImage(file,max=1500,quality=.82){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',quality))};img.src=reader.result};reader.readAsDataURL(file)})}
function bindPhoto(button,input,hidden,preview){$(button).onclick=()=>$(input).click();$(input).onchange=async()=>{const file=$(input).files[0];if(!file)return;try{const image=await fileToImage(file);$(hidden).value=image;$(preview).src=image;$(preview).hidden=false}catch(e){alert('Bildet kunne ikke leses. Prøv et annet bilde.')}}}
function download(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}

document.addEventListener('DOMContentLoaded',async()=>{
  try{await openDb();await migrateOldTripWines();await render()}catch(e){alert('Appen kunne ikke åpne den lokale databasen.')}
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));$(b.dataset.view).classList.add('active');b.classList.add('active');scrollTo(0,0)});
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});
  const newWine=async(experienceId='')=>{const travel=experienceId?(await getAll('trips')).find(x=>x.id===experienceId):null;resetWineForm(experienceId,travel?.name||'');openModal('wineModal')};$('headerAdd').onclick=()=>newWine();$('quickAdd').onclick=()=>newWine();
  $('addExperienceBtn').onclick=()=>{resetExperienceForm();openModal('experienceModal')};
  $('wineSearch').oninput=render;$('wineTypeFilter').onchange=render;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});
  $('wineList').onclick=e=>{const b=e.target.closest('[data-wine]');if(b)openWineDetail(b.dataset.wine)};
  $('experienceList').onclick=e=>{const b=e.target.closest('[data-experience]');if(b)openExperienceDetail(b.dataset.experience)};
  $('experienceWineList').onclick=e=>{const b=e.target.closest('[data-wine]');if(b)openWineDetail(b.dataset.wine)};
  bindPhoto('wineCameraBtn','wineImageCamera','wineImage','wineImagePreview');bindPhoto('wineGalleryBtn','wineImageGallery','wineImage','wineImagePreview');bindPhoto('experienceCameraBtn','experienceImageCamera','experienceImage','experienceImagePreview');bindPhoto('experienceGalleryBtn','experienceImageGallery','experienceImage','experienceImagePreview');
  $('wineForm').onsubmit=async e=>{e.preventDefault();const existingId=$('wineId').value,old=existingId?(await getAll('wines')).find(w=>w.id===existingId):null;const w={...(old||{}),id:existingId||uid(),name:$('name').value.trim(),vintage:$('vintage').value.trim(),type:$('type').value,producer:$('producer').value.trim(),country:$('country').value.trim(),region:$('region').value.trim(),grapes:$('grapes').value.trim(),tastedAt:$('tastedAt').value,place:$('place').value.trim(),people:$('people').value.trim(),experienceId:$('experienceId').value,rating:$('rating').value,notes:$('notes').value.trim(),favorite:$('favorite').checked,buyAgain:$('buyAgain').checked,image:$('wineImage').value,createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()};await put('wines',w);closeModal('wineModal');await render()};
  $('experienceForm').onsubmit=async e=>{e.preventDefault();const id=$('experienceEditId').value,old=id?(await getAll('trips')).find(x=>x.id===id):null;await put('trips',{...(old||{}),id:id||uid(),name:$('experienceName').value.trim(),date:$('experienceDate').value,text:$('experienceText').value.trim(),image:$('experienceImage').value,createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()});closeModal('experienceModal');await render()};
  $('detailEditBtn').onclick=()=>editWine(activeWineId);$('detailDeleteBtn').onclick=async()=>{if(!confirm('Vil du slette denne vinen?'))return;await remove('wines',activeWineId);closeModal('wineDetailModal');await render()};
  $('experienceAddWineBtn').onclick=()=>{closeModal('experienceDetailModal');newWine(activeExperienceId)};$('experienceEditBtn').onclick=()=>editExperience(activeExperienceId);$('experienceDeleteBtn').onclick=async()=>{if(!confirm('Slette reisen og alle vinene som er lagret på reisen?'))return;const wines=await getAll('wines');for(const w of wines.filter(x=>x.experienceId===activeExperienceId))await remove('wines',w.id);await remove('trips',activeExperienceId);closeModal('experienceDetailModal');activeExperienceId='';await render()};
  $('backupJsonBtn').onclick=async()=>{const [wines,experiences]=await Promise.all([getAll('wines'),getAll('trips')]);download(`min-vinbok-backup-${today()}.json`,'application/json',JSON.stringify({app:'Min vinbok',version:1,createdAt:new Date().toISOString(),wines,experiences},null,2))};
  $('backupCsvBtn').onclick=async()=>{const experiences=await getAll('trips'),names=Object.fromEntries(experiences.map(e=>[e.id,e.name])),wines=await getAll('wines'),cols=['name','vintage','type','producer','country','region','grapes','tastedAt','place','people','rating','favorite','buyAgain','notes','reise'];const rows=wines.map(w=>[w.name,w.vintage,w.type,w.producer,w.country,w.region,w.grapes,w.tastedAt,w.place,w.people,w.rating,w.favorite?'Ja':'Nei',w.buyAgain?'Ja':'Nei',w.notes,names[w.experienceId]||'']);download(`mine-viner-${today()}.csv`,'text/csv;charset=utf-8','\ufeff'+[cols,...rows].map(r=>r.map(csvCell).join(';')).join('\n'))};
  $('importBtn').onclick=()=>$('importInput').click();$('importInput').onchange=async()=>{const file=$('importInput').files[0];if(!file)return;try{const data=JSON.parse(await file.text()),wines=data.wines||[],experiences=data.experiences||data.trips||[];if(!Array.isArray(wines)||!Array.isArray(experiences))throw new Error();if(!confirm(`Importere ${wines.length} viner og ${experiences.length} reiser? Nåværende data erstattes.`))return;await clearStore('wines');await clearStore('trips');for(const w of wines)await put('wines',w);for(const x of experiences)await put('trips',x);await render();alert('Backupen er importert.')}catch(e){alert('Filen er ikke en gyldig backup fra Min vinbok.')}finally{$('importInput').value=''}};
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
});
